export default function PricingSection() {
  return (
    <section className="ρd__all ρd__section ρjm6No" id="prices"><div className="ρd__all ρd__div ρqsn93"><div className="ρd__all ρd__div ρt ρpiYef"> ¿Cuánto te sentirías cómodo invirtiendo en tu terapia por sesión?
</div><div className="ρd__all ρd__div ρt ρkhFtw">Contamos con terapeutas con diferentes niveles de experiencia, lo que da como resultado una variedad de valores.</div><div className="ρd__all ρd__div ρt ρxwR7A">Elige una opción:</div><div className="ρd__all ρd__div ρguAeX"><div className="ρd__all ρd__div ρglvE"><div className="ρd__all ρd__div ρcWTkg"><a className="ρd__all ρd__button ρr-jrVUo ρdss ρmns ρtns-jrVUo ρtns-ohDid ρwzF7P ρi ρaUwZx" href="https://lps.eurekka.me/es-appointment/?value=35&amp;source=padrao+undefined+undefined+undefined+undefined"><div className="ρd__all ρd__div ρtOdPh"><span className="__wab_slot ρs ρeBk1J"><div className="ρd__all ρd__div ρiiKhD"><div className="ρd__all ρd__div ρu9Awx"><div className="ρd__all ρd__div ρt ρz7XtT">US$ 35.00
por sesión</div></div></div></span></div></a></div></div><div className="ρd__all ρd__div ρwxnlt"><div className="ρd__all ρd__div ρkBiqw"><a className="ρd__all ρd__button ρr-jrVUo ρdss ρmns ρtns-jrVUo ρtns-ohDid ρwzF7P ρi ρn8XbZ" href="https://lps.eurekka.me/es-appointment/?value=40&amp;source=padrao+undefined+undefined+undefined+undefined"><div className="ρd__all ρd__div ρtOdPh"><span className="__wab_slot ρs ρeBk1J"><div className="ρd__all ρd__div ρt ρmMqji">US$ 40.00
por sesión</div></span></div></a></div><div className="ρd__all ρd__div ρ_6WMmX"><a className="ρd__all ρd__button ρr-jrVUo ρdss ρmns ρtns-jrVUo ρtns-ohDid ρwzF7P ρi ρkjcHk" href="https://lps.eurekka.me/es-appointment/?value=50&amp;source=padrao+undefined+undefined+undefined+undefined"><div className="ρd__all ρd__div ρtOdPh"><span className="__wab_slot ρs ρeBk1J"><div className="ρd__all ρd__div ρt ρwlFOu">US$ 50.00
por sesión</div></span></div></a></div></div><div className="ρd__all ρd__div ρbEydg"><div className="ρd__all ρd__div ρmMr2O"><a className="ρd__all ρd__button ρr-jrVUo ρdss ρmns ρtns-jrVUo ρtns-ohDid ρwzF7P ρi ρdMlO" href="https://lps.eurekka.me/es-appointment/?value=60&amp;source=padrao+undefined+undefined+undefined+undefined"><div className="ρd__all ρd__div ρtOdPh"><span className="__wab_slot ρs ρeBk1J"><div className="ρd__all ρd__div ρt ρgTdOl">US$ 60.00
por sesión</div></span></div></a></div><div className="ρd__all ρd__div ρ_02Msi"><a className="ρd__all ρd__button ρr-jrVUo ρdss ρmns ρtns-jrVUo ρtns-ohDid ρwzF7P ρi ρlVqiQ" href="https://lps.eurekka.me/es-appointment/?value=70&amp;source=padrao+undefined+undefined+undefined+undefined"><div className="ρd__all ρd__div ρtOdPh"><span className="__wab_slot ρs ρeBk1J"><div className="ρd__all ρd__div ρt ρu5Os">US$ 70.00
por sesión</div></span></div></a></div></div></div><div className="ρd__all ρd__div ρt ρd36M2">Tu cita será confirmada después del pago</div></div></section>
  );
}
